version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: mynodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    depends_on:
      - influxdb
      - mosquitto
    networks:
      - mynetwork

  influxdb:
    image: influxdb:1.8
    container_name: myinfluxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
      - ./init_influxdb:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_DB=power_monitor
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    networks:
      - mynetwork

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mymosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
      - ./mosquitto_config:/mosquitto/config
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
